# Functions / Methods in Python
# general syntax

# def function_name ( parameter1, parameter2 ) :
#   [indent] CODE BLOCK

# There is no closing bracket like in a majority of other languages. The white spacing matters here
# what ever code is indented TO THE SAME level WILL be considered a part of that CLASS, FUNCTION, IF, or LOOP statement.


def adding_function(x, y):
    print(x + y)


print("hello")
# we need another line of code at a different indentation for python to consider "the end of the function"
# Standard PEP8 conventions for space before and after classes / functions

# Calling our function:
adding_function(15, 38)


# Project Euler Problem 2: https://projecteuler.net/problem=2

# Problem 2         : Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#                     By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#                     By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#                     find the sum of the even-valued terms.

